<?xml version="1.0" encoding="utf-8"?><Database Name="Muestra2" Class="MuestraDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Muestra2;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Muestra2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Departamentos" Member="Departamentos">
    <Type Name="Departamentos">
      <Column Name="idDept" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Departamento" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Ubicacion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Departamentos_Empleados" Member="Empleados" ThisKey="idDept" OtherKey="idDept" Type="Empleados" />
    </Type>
  </Table>
  <Table Name="dbo.Empleados" Member="Empleados">
    <Type Name="Empleados">
      <Column Name="idEmp" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Genero" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Salario" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idDept" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Departamentos_Empleados" Member="Departamentos" ThisKey="idDept" OtherKey="idDept" Type="Departamentos" IsForeignKey="true" />
    </Type>
  </Table>
</Database>